[project]
name = "hotspot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awswrangler==3.14.0",
    "boto3==1.41.5",
    "botocore[crt]>=1.41.6",
    "pandas==2.3.3",
    "streamlit==1.51.0",
]
