[project]
name = "hotspot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "awswrangler==3.4.2",
    "boto3==1.28.40",
    "pandas==2.3.3",
    "streamlit==1.28.2",
]
